@startuml
hide footbox

participant "InternTrack" as InternTrack <<class>>
participant "ApplicationList" as ApplicationList <<class>>
participant "Parser" as Parser <<class>>
participant "Ui" as Ui <<class>>
participant "Storage" as Storage <<class>>

[-> InternTrack : handleAddCommand()
activate InternTrack

InternTrack -> ApplicationList : addApplications()
activate ApplicationList

ApplicationList -> Parser : createApplication()
activate Parser

create "newApplication:Application" as Application
Parser -> Application : Application()
activate Application
Application --> Parser ::Application
deactivate Application

Parser --> ApplicationList : :Application
deactivate Parser

ApplicationList --> InternTrack : newApplication:Application
deactivate ApplicationList

InternTrack -> Ui : printAddApplication()
activate Ui
Ui --> InternTrack
deactivate Ui

InternTrack -> Storage : saveApplications()
activate Storage
Storage --> InternTrack
deactivate Storage

[<-- InternTrack
deactivate InternTrack

@enduml