@startuml
hide footbox

participant ":InternTrack" as InternTrack
participant ":ApplicationList" as ApplicationList
participant ":Parser" as Parser
participant ":Ui" as Ui
participant ":Storage" as Storage

[-> InternTrack : handleAddCommand()
activate InternTrack

InternTrack -> ApplicationList : addApplications()
activate ApplicationList

ApplicationList -> Parser : createApplication()
activate Parser

create "newApplication:Application" as Application
Parser -> Application : Application()
activate Application
Application --> Parser ::Application
deactivate Application

Parser --> ApplicationList : :Application
deactivate Parser

ApplicationList --> InternTrack : newApplication:Application
deactivate ApplicationList

InternTrack -> Ui : printAddApplication()
activate Ui
Ui --> InternTrack
deactivate Ui

InternTrack -> Storage : saveApplications()
activate Storage
Storage --> InternTrack
deactivate Storage

[<-- InternTrack
deactivate InternTrack

@enduml