@startuml
actor User
participant "Ui" as Ui<<class>>
participant "InternTrack" as InternTrack<<class>>

User -> Ui : list
Ui->InternTrack : handleListCommand()
activate InternTrack
InternTrack -->Ui
deactivate InternTrack
Ui --> User

@enduml