@startuml
actor User
participant Ui
participant InternTrack
participant System

User -> Ui : list
Ui->InternTrack : handleListCommand()
InternTrack -> System : System.out.println()
System ->InternTrack
InternTrack ->Ui
Ui -> User

@enduml