@startuml
actor User
participant ":Ui" as  Ui
participant ":InternTrack" as InternTrack
participant ":Parser" as Parser
participant ":ApplicationList" as ApplicationList

User -> Ui : sort by/CRITERIA [FLAG]
Ui -> InternTrack : handleSortCommand()
activate InternTrack
InternTrack -> Parser : parseSortCriteria()
activate Parser
Parser --> InternTrack :
deactivate Parser
InternTrack -> ApplicationList : sortApplicationsByCriteria()
activate ApplicationList
ApplicationList --> InternTrack
deactivate ApplicationList
InternTrack ->Ui :printSortedApplications()
deactivate InternTrack
Ui-->User
@enduml