@startuml
actor User
participant "Ui" as  Ui<<class>>
participant "InternTrack" as InternTrack<<class>>
participant "Parser" as Parser<<class>>
participant "ApplicationList" as ApplicationList<<class>>

User -> Ui : sort by/CRITERIA [FLAG]
Ui -> InternTrack : handleSortCommand()
activate InternTrack
InternTrack -> Parser : parseSortCriteria()
activate Parser
Parser --> InternTrack :
deactivate Parser
InternTrack -> ApplicationList : sortApplicationsByCriteria()
activate ApplicationList
ApplicationList --> InternTrack
deactivate ApplicationList
InternTrack ->Ui :printSortedApplications()
deactivate InternTrack
Ui-->User
@enduml