@startuml
actor User
participant Ui
participant InternTrack
participant Parser
participant ApplicationList

User -> Ui : sort by/CRITERIA [FLAG]
Ui -> InternTrack : handleSortCommand()
InternTrack -> Parser : parseSortCriteria()
Parser -> InternTrack :
InternTrack -> ApplicationList : sortApplicationsByCriteria()
ApplicationList -> InternTrack
InternTrack ->Ui :printSortedApplications()
Ui->User
@enduml