@startuml
actor User
participant ":Ui" as Ui
participant ":InternTrack" as InternTrack
participant ":Parser" as Parser
participant ":SummaryCommand" as SummaryCommand

User -> Ui : summary
Ui -> InternTrack : handleSummaryCommand()
activate InternTrack
InternTrack -> Parser : parseSummaryCommand()
activate Parser
Parser --> InternTrack
deactivate Parser

InternTrack -> SummaryCommand : execute(applications)
activate SummaryCommand
SummaryCommand --> InternTrack
deactivate SummaryCommand
InternTrack -> Ui : printSummaryReport()
deactivate InternTrack
Ui --> User
@enduml